//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServicioUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuario.IUsuario")]
    public interface IUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioAdd", ReplyAction="http://tempuri.org/IUsuario/UsuarioAddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result UsuarioAdd(ML.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioAdd", ReplyAction="http://tempuri.org/IUsuario/UsuarioAddResponse")]
        System.Threading.Tasks.Task<ML.Result> UsuarioAddAsync(ML.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioDelete", ReplyAction="http://tempuri.org/IUsuario/UsuarioDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result UsuarioDelete(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioDelete", ReplyAction="http://tempuri.org/IUsuario/UsuarioDeleteResponse")]
        System.Threading.Tasks.Task<ML.Result> UsuarioDeleteAsync(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioUpdate", ReplyAction="http://tempuri.org/IUsuario/UsuarioUpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result UsuarioUpdate(ML.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioUpdate", ReplyAction="http://tempuri.org/IUsuario/UsuarioUpdateResponse")]
        System.Threading.Tasks.Task<ML.Result> UsuarioUpdateAsync(ML.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioGetAll", ReplyAction="http://tempuri.org/IUsuario/UsuarioGetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result UsuarioGetAll(ML.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioGetAll", ReplyAction="http://tempuri.org/IUsuario/UsuarioGetAllResponse")]
        System.Threading.Tasks.Task<ML.Result> UsuarioGetAllAsync(ML.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioGetById", ReplyAction="http://tempuri.org/IUsuario/UsuarioGetByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result UsuarioGetById(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/UsuarioGetById", ReplyAction="http://tempuri.org/IUsuario/UsuarioGetByIdResponse")]
        System.Threading.Tasks.Task<ML.Result> UsuarioGetByIdAsync(int IdUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioChannel : PL_MVC.ServicioUsuario.IUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<PL_MVC.ServicioUsuario.IUsuario>, PL_MVC.ServicioUsuario.IUsuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.Result UsuarioAdd(ML.Usuario usuario) {
            return base.Channel.UsuarioAdd(usuario);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UsuarioAddAsync(ML.Usuario usuario) {
            return base.Channel.UsuarioAddAsync(usuario);
        }
        
        public ML.Result UsuarioDelete(int IdUsuario) {
            return base.Channel.UsuarioDelete(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UsuarioDeleteAsync(int IdUsuario) {
            return base.Channel.UsuarioDeleteAsync(IdUsuario);
        }
        
        public ML.Result UsuarioUpdate(ML.Usuario usuario) {
            return base.Channel.UsuarioUpdate(usuario);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UsuarioUpdateAsync(ML.Usuario usuario) {
            return base.Channel.UsuarioUpdateAsync(usuario);
        }
        
        public ML.Result UsuarioGetAll(ML.Usuario usuario) {
            return base.Channel.UsuarioGetAll(usuario);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UsuarioGetAllAsync(ML.Usuario usuario) {
            return base.Channel.UsuarioGetAllAsync(usuario);
        }
        
        public ML.Result UsuarioGetById(int IdUsuario) {
            return base.Channel.UsuarioGetById(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UsuarioGetByIdAsync(int IdUsuario) {
            return base.Channel.UsuarioGetByIdAsync(IdUsuario);
        }
    }
}
